version: "3.7"
services:
  app:
    build:
      args:
        user: app_user
        uid: 1000
      context: ./docker/php/
      dockerfile: Dockerfile
    image: app
    container_name: laravel-project-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-project

  nginx:
    image: nginx:1.17-alpine
    container_name: laravel-project
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel-project

  db:
    image: mysql:5.7
    container_name: laravel-project-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel-project


networks:
  laravel-project:
    driver: bridge
